# -*- coding: utf-8 -*-
"""
Created on Thu Sep 12 17:51:38 2024

@author: nesseler
"""

ePhys_parameter_dict = {'rheobase_abs' : {'ax_min' : -50,
                                          'ax_max' : 250,
                                          'pad' : 5,
                                          'step' : 50,
                                          'stepminor' : 10,
                                          'label' : 'Absolute rheobase [pA]'},
                        'rheobase_rel' : {'ax_min' : -50,
                                          'ax_max' : 250,
                                          'pad' : 5,
                                          'step' : 50,
                                          'stepminor' : 10,
                                          'label' : 'Relative rheobase [pA]'},
                        'rheobasespike_ttopeak' : {'ax_min' : 0.5,
                                                   'ax_max' : 1.5,
                                                   'pad' : (1.5 - 0.5) * 0.05,
                                                   'step' : 0.5,
                                                   'stepminor' : 0.1,
                                                   'label' : 'Rheobase spike time to peak [ms]'},
                        'rheobasespike_trise' :   {'ax_min' : 0.2,
                                                   'ax_max' : 0.5,
                                                   'pad' : (0.5 - 0.2) * 0.05,
                                                   'step' : 0.1,
                                                   'stepminor' : 0.05,
                                                   'label' : 'Rheobase spike rise time [ms]'},
                        'rheobasespike_ttoAHP' :  {'ax_min' : 1,
                                                   'ax_max' : 4.5,
                                                   'pad' : (4.5 - 1) * 0.05,
                                                   'step' : 1,
                                                   'stepminor' : 0.1,
                                                   'label' : 'Rheobase spike time to (fast) AHP [ms]'},
                        'rheobasespike_FWHM' :    {'ax_min' : 0.5,
                                                   'ax_max' : 2,
                                                   'pad' : (2 - 0.5) * 0.05,
                                                   'step' : 0.5,
                                                   'stepminor' : 0.1,
                                                   'label' : 'Rheobase spike FWHM [ms]'},
                        'max_freq' :              {'ax_min' : 0,
                                                   'ax_max' : 85,
                                                   'pad' : (85 - 0) * 0.05,
                                                   'step' : 10,
                                                   'stepminor' : 5,
                                                   'label' : 'Max. AP frequency [Hz]'},
                        'max_inst_freq' :         {'ax_min' : 0,
                                                   'ax_max' : 200,
                                                   'pad' : (200 - 0) * 0.05,
                                                   'step' : 20,
                                                   'stepminor' : 5,
                                                   'label' : 'Max. AP frequency [Hz]'},
                        'max_inst_initial_freq' : {'ax_min' : 0,
                                                   'ax_max' : 200,
                                                   'pad' : (200 - 0) * 0.05,
                                                   'step' : 20,
                                                   'stepminor' : 5,
                                                   'label' : 'Max. AP frequency [Hz]'}}


axis_dict = {'r_input' : {'ax_min' : -50,
                          'ax_max' : 1300,
                          'pad' : None,
                          'step' : 200,
                          'stepminor' : 50,
                          'label' : 'Input resistance [MOhm]',
                          'start_at_0' : True},
             'tau_mem' : {'ax_min' : 0,
                          'ax_max' : 40,
                          'pad' : None,
                          'step' : 10,
                          'stepminor' : 2,
                          'label' : 'Membrane time constant [ms]'},
             'c_mem' : {'ax_min' : 0,
                        'ax_max' : 100,
                        'pad' : None,
                        'step' : 20,
                        'stepminor' : 5,
                        'label' : 'Membrane capacitance [pF]'},
             'v_rest' : {'ax_min' : -90,
                         'ax_max' : -70,
                         'pad' : None,
                         'step' : 5,
                         'stepminor' : 1,
                         'label' : 'Resting membrane potential [mV]'},
             'sagdelta' : {'ax_min' : 0,
                           'ax_max' : 25,
                           'pad' : None,
                           'step' : 5,
                           'stepminor' : 1,
                           'label' : 'Sag delta potential [mV]'},
             'rheobase_rel' : {'ax_min' : 0,
                               'ax_max' : 450,
                               'pad' : None,
                               'step' : 100,
                               'stepminor' : 25,
                               'label' : 'Rheobase current [pA]'},
             'rheobasespike_vthreshold' : {'ax_min' : -75,
                                           'ax_max' : -35,
                                           'pad' : None,
                                           'step' : 10,
                                           'stepminor' : 5,
                                           'label' : 'Rheobase spike threshold [mV]'},
             'rheobasespike_vamplitude' : {'ax_min' : 70,
                                           'ax_max' : 130,
                                           'pad' : None,
                                           'step' : 10,
                                           'stepminor' : 5,
                                           'label' : 'Rheobase spike amplitude [mV]'},
             'rheobasespike_ttoPeak' : {'ax_min' : 0.5,
                                        'ax_max' : 1.5,
                                        'pad' : None,
                                        'step' : 0.5,
                                        'stepminor' : 0.1,
                                        'label' : 'Rheobase spike time to peak [ms]'},
             'rheobasespike_FWHM' : {'ax_min' : 0.5,
                                     'ax_max' : 2.0,
                                     'pad' : None,
                                     'step' : 0.5,
                                     'stepminor' : 0.1,
                                     'label' : 'Rheobase spike FWHM [ms]'},
             'rheobasespike_AHPamplitude' : {'ax_min' : -20,
                                             'ax_max' : 10,
                                             'pad' : None,
                                             'step' : 10,
                                             'stepminor' : 2,
                                             'label' : 'Rheobase spike fast AHP amplitude [mV]'},
             'rheobasespike_ttoAHP' : {'ax_min' : 1,
                                       'ax_max' : 5,
                                       'pad' : None,
                                       'step' : 1,
                                       'stepminor' : 0.5,
                                       'label' : 'Rheobase spike time to fast AHP [ms]'},
             'delta_vrest2vthres' : {'ax_min' : 0,
                                     'ax_max' : 50,
                                     'pad' : None,
                                     'step' : 10,
                                     'stepminor' : 2,
                                     'label' : 'Potential delta between v_rest and v_threshold [mV]'},
             'i_maxfreq' : {'ax_min' : 0,
                            'ax_max' : 650,
                            'pad' : None,
                            'step' : 100,
                            'stepminor' : 25,
                            'label' : 'Input current for max. firing frequency [pA]'},
             'i_maxinitinstfreq' : {'ax_min' : 0,
                                    'ax_max' : 1200,
                                    'pad' : None,
                                    'step' : 100,
                                    'stepminor' : 50,
                                    'label' : 'Input current for max. firing frequency [pA]'},
             'spike_amplitude_adaptation_ratio' : {'ax_min' : 0,
                                                   'ax_max' : 1,
                                                   'pad' : None,
                                                   'step' : 0.2,
                                                   'stepminor' : 0.05,
                                                   'label' : 'Spike amplitude adaptation ratio'},
             'spike_FWHM_adaptation_ratio' : {'ax_min' : 0,
                                              'ax_max' : 6,
                                              'pad' : None,
                                              'step' : 1,
                                              'stepminor' : 0.5,
                                              'label' : 'Spike FWHM adaptation ratio'},
             'freq_adaptation_ratio' : {'ax_min' : 0,
                                        'ax_max' : 1,
                                        'pad' : None,
                                        'step' : 0.2,
                                        'stepminor' : 0.05,
                                        'label' : 'Spike FWHM adaptation ratio'}}